kelektiv/node-cron

lib/cron.js
Before this commit, `lib/cron.js` was a hodge podge
of tab indentation and two-space indentation.
This commit changes all tab indents to two spaces.
It might be noted that for the first three lines (2-4), I left the indentation at 4 spaces (well, from 2 tabs) - if this is not well received (ahh! no!) it can be changed back to two spaces.
=> Fixes indentation

lib/cron.js
`cron` was using `.tz` which was recently deprecated in https://github.com/moment/moment/issues/1779. This PR fixes the deprecation notice that `moment` was throwing.
=> Fixes the deprecation notice from moment.

lib/cron.js
Hi!
Thank you for this awesome module.
I'm using it everyday with the timezone set (Europe/Paris), and today, all of my crons have 1 hour late.
I did some tests to see if the timezone is still working:
```javascript
var cronJob = require('cron').CronJob;
new cronJob({
cronTime: '*/5 * 14 * * *', // every 5 seconds at 14h (it is 14h in France actually)
timeZone: 'Europe/Paris',
onTick: function () {
console.log(new Date);
},
start: true
});
```
-> No console.log displayed.
I tried on my computer (french date) with and without the timeZone set, and that how I found what line to change in the code based on the moment Timezone documentation.
I'm using my fork actually on my project, but I would like to use your as soon as possible.
If you're ok to merge, can you please bump the version?
Thank …
=> Fix the timezone issue from 1.0.7

lib/cron.js, tests/test-cron.js
Before this commits, CronJob.prototype.setTime throw not error instance but string instance. so thrown error stack is `undefined`.
Show an example below.
```
$ cat hoge.js                                                                                                                                                 
var CronJob = require("./lib/cron").CronJob;
var job = new CronJob("* * * * *");
try {
job.setTime(new Date());
} catch (err) {
console.log(err.stack);
}
$ node hoge.js 
undefined
```
Modified setTIme to throw error instance.
=> Modified CronJob.prototype.setTime to throw error instance

README.md
The README links to crontab.org, which provides examples with 5 fields and
minute granularity. node-cron expects the leftmost value to describe the
granularity in seconds. This inconsistency led me to misinterpret the running
times in a cron.CronJob.
=> Note discrepancy between cron formats

lib/cron.js
when using node-cron as a base for an agenda, it is useful to be able to easily calculate the next i occurences of a cron-job for displaying purposes etc.
the nextDates takes a positive integer i and returns an array containing the next i dates for the cron job.
=> Add a nextDates method to be able to easily get the next i occurences of a cronjob.

lib/cron.js, tests/test-cron.js
This patch prevents onTick() to be called twice if setTimeout callback was called earlier than expected due to time adjustment. It just measures how much time passed since we set timeout and if it's less than it should it reschedules onTick call.
=> Reschedule onTick if time was ajusted back GH-249

README.md
The job.running variable can be used to get status of job, but have to use a slightly modified syntax
This PR addresses https://github.com/kelektiv/node-cron/issues/265
Hi,
This is my first time creating a documentation related PR. Please let me know, if I can make any improvements on this
=> Add example for job.running in README.md

lib/cron.js
Update undocumented `exports.job()` function to accept and pass all the arguments in the `CronJob` object's constructor function.
By the way, I prefer calling `cron.job()` over instantiating a `new CronJob()` manually. One reason is that it plays nicer with [this ESLint rule](http://eslint.org/docs/rules/no-new) when I don't need to store the job in a variable. Is there a reason `cron.job()` is undocumented, or should it be added to the docs as an alternate syntax? I'd be happy to help in that case.
=> Match exports.job() signature to CronJob constructor

lib/cron.js
1. Added a missing argument in the `job` function
2. Fixed bug when calling the `CronJob` constructor from the `job` function (incorrectly checking the number of arguments)
=> Two small bugfixes

lib/cron.js, tests/test-crontime.js
Issue:
```js
const cron = require('cron');
const cronTime = new cron.CronTime('0 */10 * * * *');
const x = cronTime._getNextDateFrom(new Date("2018-08-10T02:20:00.009Z"))
console.log(x);
```
Observe: `x`
Expect: `x` should be `2018-08-10T02:30:00.009Z` (next 10 mins coz the cron pattern is each 10 mins)
Actual: `2018-08-10T02:20:00.009Z` (unchange).
Affect: This issue will cause `cron` to repeat triggering `onTick` many many times within one second.
=> fix issue when cronTime _getNextDateFrom not calculate correctly

lib/cron.js, tests/test-crontime.js
Hi @ncb000gt
As Discussed in the previous PR,  this fix will cover the following cases:
extracting the next day from the following cron strings
```
* * * * *
*/15 *  * * *
* 5 * * * *
```
and many others where * is used in  minute/hour/day/week
Thanks alot.
=> Fixing _getNextDateFrom function logic

lib/cron.js
Check the .unref() method exists and call it each
time the timer is started.
=> Do not keep an otherwise finished program running.

lib/cron.js
Fixing bug in that resulted from my faulty logic in my last PR. I'm extremely sorry for any inconvenience caused .
**Summary of what happened:**
My previous fix assumed that there were multiple instances of daysOfMonth for each month ( which is not valid) . This resulted in fixing the days to only match  month  February. 
Now I'm only fixing the days only if all months fail, ie: choosing day of month 45 ( not found in any month )
this will fix the following issues:
#366 #372 #371 #373 
clearly current tests were not able to detect this bug. after reviewing the current tests i realized that this was due to "start" attribute set to true such as in the first test
Again, I'm so sorry for causing this problem.
=> fixing bug in version 1.4.0

lib/cron.js, package-lock.json, tests/test-crontime.js
The current implementation ignores the UTC offset when it's specified as the number 0, so if you create a job using the command `new CronJob('0 16 * * *', { utcOffset: 0, start: true, ... })` at `15:59:59 GMT+2` it gets executed a second later, whereas it should actually be executed two hours later, at `18:00 GMT+2`/`16:00 UTC`.
The underlying library, moment, does accept `0`, so we only need to pass it over.
This PR replaces the naive if-based truth checks with the more restricted `undefined` checks.
=> Accept 0 as a valid UTC offset

README.md
Ran into this issue recently; I had assumed that setTime() kept the job running. Had to take a look at the source code to see that the job get stopped first. A small update that clarifies things.
=> Update README to note that setTime() stops the job

lib/cron.js
Alternate for [Remove hard limit on max iters](https://github.com/kelektiv/node-cron/commit/57632b0c06c56e82f40b740b8d7986be43842735#r31926799) (see comments)
=> Better detection an infinite loop

lib/cron.d.ts, package.json
Feel free contribute and keep improving this TS definitions.
=> [starter] added ts definitions

lib/cron.js, tests/cron.test.js, tests/crontime.test.js
Hello,
Some cron patterns like `* * * * * * * *` or `* * * * 1234` are incorrect but don't throw errors at job creation.
I propose to improve the detection of such incorrect patterns.
=> Improve detection of incorrect cron pattern

lib/cron.js, tests/cron.test.js
Resolves #449. A range with a step and no upper limit provided should default to the full range. E.g. `"1/2 * * * * *"` should be the same as `"1-59/2 * * * * *"`.
=> Range upper limit should default to highest value when step is provided

README.md
I know that there is a note below code which tells that you need to start a job. But i think it's better when example is fully working
=> Add job.start() to example code

lib/cron.js
1. Fix error occurred when trying:
Example:
```
var time = new cron.CronTime('* * * * * *'); // return an object
job.setTime(time); // time must be an instance of CronTime.
```
2. Start job again
=> Fix setTime and start job

.github/workflows/nodejs.yml, package-lock.json, package.json, tests/cron.test.js
updated a bunch of packages that have vulnerabilities (just in package-lock.json for now, I can try updating package.json to fix the rest if you like). I can also see if I can get builds running again. is that the workflow that's awaiting approval?
Additional vulns are all Jest deps. the fix involves updating to Jest 27.5.1 which I can attempt as long as someone's willing to double check the tests afterward
=> update vulnerable packages

lib/time.js
we can close the ~40 duplicate issues and people can stop creating new ones that all likely focus on the same bug. if we find there are different causes for the 5 second difference in execution we can create multiple canonical issues to address the different causes
=> update maximum iterations error to refer to canonical GitHub issue

lib/time.js, tests/crontime.test.js
This fixes issue #638 
it does this by 
1) detecting a forward jump in time happened after changing the time of a date in _getNextDate()
2) Scanning the jumped-over range for matches with the time pattern.
What made (2) extra tricky is that apparently, DST is not uniformly 1 hour. That made things a little more complicated.
Right now the skipped range scanner assumes a forward jump is 1 minute to 23 hrs 59 minutes long, and does not roll over days.
This PR also fixes a test that was failing on the master branch, by disambiguating a DateTime (the ISO string represented 2 possible times due to a DST backwards shift, and luxon picked the unfavorable one).
**An important** thing to know about this change, is that it also fixes another, more minor bug with _getNextDate(), namely that a …
=> Fix infinite looping bugs with recurrent tasks around DST

lib/job.js, tests/cron.test.js
I started by wrapping the `setTime` test cases in a `describe`, so changes might not be obvious for `tests/cron.test.js`. Please see the commits detail for better readability.
Fixes #598.
=> fix: don't start job in setTime if it wasn't running

package.json, types/index.d.ts
Imported type definitions from [@types/cron](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/cron). Tested in a Typescript project, and the types were successfully detected by the compiler.
=> feat: import type definitions from @types/cron

.github/workflows/release.yml, .github/workflows/test.yml, .releaserc
This PR updates GitHub Actions & Semantic Release configuration files in order to support beta & maintenance releases.
- https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches
- https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/release-workflow/pre-releases.md
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore
=> ci: add support for beta & maintenance releases

.github/workflows/test.yml, .husky/commit-msg, .releaserc, README.md
This PR updates the default branch name to match the new Git setup
=> chore: update default branch name

README.md, lib/time.js, tests/crontime.test.js
=> feat!: UNIX standard alignments

lib/time.js, tests/cron.test.js
This change is inspired by [cronie's `crond`](https://github.com/cronie-crond/cronie/blob/master/src/cronnext.c).
It replaces the 5 seconds timeout in the `_getNextDateFrom` while loop by a maximum date in the future (8 years).
Fixes #467.
Closes #499.
In environments with limited resources (CPU/memory), it may take more than 5 seconds to find the next date. This throws an error (see #467), while it should only take the time it needs and find the occurence.
Using [the `systemd-run` command](https://github.com/kelektiv/node-cron/issues/467#issuecomment-1580693046), I've been able to compare the behavior of test runs between the `main` branch and this version and to confirm that these changes have all tests passing correctly in a low resources environment.
*This issue was initially …
=> fix: replace loop timeout by max match date

README.md, lib/job.js, tests/cron.test.js
- Make sure that `nextDates` return an array(as described in the README.md) even if it's called without an argument(in this case an empty array)
- Add `nextDate` description in the README.md
- `nextDates` return a moment object, if it's called without an argument
- This change could break someone's code!!
- If this PR is not accepted, I will make another PR just to update the description of the behaviour of `nextDates` function in the READM.md
=> fix!: return empty array from nextDates when called without argument

package-lock.json, package.json
- added `@types/luxon` to dependencies
- updated Luxon from `v3.2.1` to `v3.3.0` (avoided `v3.4.0` since types aren't available for that version yet).
Fixes #688.
This library needs to depend on `@types/luxon` since we now export our own types. See the related issue for the error this fixes.
- checked that TypeScript now correctly loads the Luxon types
- ran tests locally
=> fix(deps): update dependency luxon to v3.3.0 & add @types/luxon

lib/time.js, tests/crontime.test.js
When providing the invalid value `0` as the upper limit in a range (e.g. `2-0`), the library was not detecting the error due to the use of the `||` operator, which considers `0` & `undefined` the same way.
I have replaced the operator to check specifically for `undefined` in order to detect the invalid value `0`.
Fixes #654.
I have extended an existing test case to check for invalid ranges and added a test case that checks all valid ranges are accepted.
=> fix: fix range parsing when upper limit = 0

.github/workflows/test.yml, package-lock.json, package.json, types/index.test-d.ts
Imported and adapted the [types test file from `@types/cron`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/34872661a2fd0a6a43fe8da464bc2ec07ad49169/types/cron/cron-tests.ts).
*Note: The tests won't pass until #689 is merged since they detect the issue it fixes.*
- #688
This adds more safety to our workflow regarding TypeScript types. Note that this only statically checks the types, so there is no assurance the runtime types would match.
=> test: add TS types check

README.md
to be merged once https://github.com/kelektiv/node-cron/pull/694 is in `beta`.
=> docs(readme): remove outdated informations

.github/ISSUE_TEMPLATE/feature.yaml, CONTRIBUTING.md
I updated the labels today, this PR reflects these changes in the issue templates and contributing documentation.
=> chore: reflect repository label changes

tests/cron.test.ts, tests/crontime.test.ts
Make sure every test calls `expect()`, even asynchronously.
> `(method) jest.Expect.hasAssertions(): void`
> Verifies that at least one assertion is called during a test. This is often useful when testing asynchronous code, in order to make sure that assertions in a callback actually got called.
N/A
Since we sometimes use `expect()` in the `onTick` callback, tests could pass if the callback is never called, resulting in bugs not being detected by our test suites.
Temporarily removed the `cloc.tick()` call on an asynchronous test, successfully failing the test where it was previously succeeding.
=> test: check at runtime that all tests call expect

src/index.ts, src/job.ts, src/time.ts, src/types/cron.types.ts, tests/cron.test.ts
See related issue.
Closes https://github.com/kelektiv/node-cron/issues/703.
See related issue.
added a new test & removed type casting from existing tests.
=> feat: improve context, onTick & onComplete typings

src/job.ts, tests/cron.test.ts
Update the internal `lastExecution` variable when running `onTick`, not when checking if we should run `onTick` or set a new timeout.
Fixes https://github.com/kelektiv/node-cron/issues/710.
See related issue.
Added test case. See [the failing test workflow](https://github.com/kelektiv/node-cron/actions/runs/6382788543/job/17322106840?pr=711) before pushing the fix.
=> fix: fix lastDate() value for intervals > 25 days

.github/renovate.json
this PR updates Renovate configuration as follow:
- migrate `config:base` to `config:recommended` (name change in Renovate, same behavior)
- enable [`security:openssf-scorecard` preset](https://docs.renovatebot.com/presets-security/#securityopenssf-scorecard)
- enable [`osvVulnerabilityAlerts` option](https://docs.renovatebot.com/configuration-options/#osvvulnerabilityalerts)
- use `build` commit type for dependencies instead of `fix` (as specified in [most semantic](https://github.com/insurgent-lab/conventional-changelog-preset#commit-types) [commit types](https://github.com/angular/angular/blob/92113d73dd38d0285e25e8d678c240cf4aa8834a/CONTRIBUTING.md#type) conventions)
- merge `monorepo:semantic-release`, `monorepo:commitlint`, `@insurgentlab/conventional-changelog-preset` and …
=> ci(renovate): update configuration

src/job.ts, src/types/cron.types.ts, tests/cron.test.ts
this is a type-only change that allows callbacks to return a promise. this was already possible before migrating the codebase to TypeScript, but it wasn't reflected correctly in our typings.
N/A
while working on the `@nestjs/schedule` PR to upgrade to `cron@3.x`, I got a SonarLint warning about passing an async function to onTick.
added test case with async `onTick`.
=> fix: allow callbacks to return a promise

src/job.ts, src/time.ts, tests/cron.test.ts
initially, set the internal variable `runOnce` correctly when passing an actual date to `setTime`. previously this was only done in the constructor.
since it is only used in [one place](https://github.com/kelektiv/node-cron/blob/24f31caf4dd180d834f4f3ead2576cb80de9a4b8/src/job.ts#L261) and as to limit this kind of error, I then removed the `runOnce` property completely (we now check directly if `this.cronTime` is a real date). we do not consider this a breaking change since it was not referenced in the API documentation).
Fixes #739.
Fixes an issue when after creating a job with a cron expression and using `setTime` with an actual date, the job attempts to run multiple times.
added test case provided by #739's OP.
=> fix: set runOnce when actual date is given to setTime

src/time.ts, tests/crontime.test.ts
Please take a look at the related issue for more information.
Fixes #742.
=> fix: detect multiple zeros as an invalid step

README.md
Refactored the Readme file into a more readable and standard readme
Closes #441.
=> docs(readme): API documentation overhaul

src/job.ts
add `runOnce` back to CronJob, this time as a getter to shadowing `this.cronTime.realDate` value.
https://github.com/kelektiv/node-cron/pull/740#issuecomment-1777662358
removing this property was a breaking change.
=> fix: re-add runOnce property to CronJob

src/job.ts, src/time.ts, tests/cron.test.ts
This PR restores the original `runOnce` property, which was changed in #740 without considering it a breaking change since it was an undocumented internal property. That was a mistake because consumers relied on it.
The property was added back *as a read-only getter* in #751, which was another naive decision from me, because not only did consumers rely on reading it, but it seems (based on the Renovate passing tests percentage below) that they actually also mutate the property to change their jobs' behavior.
> ![image](https://github.com/kelektiv/node-cron/assets/11234273/b0706eac-7c39-48cb-bb17-de6abaf559f6)
- #739
- #740
- #751
Test case already present from #740.
=> fix: revert runOnce breaking changes

.github/workflows/test.yml
Skip the `push` event if the workflow detects an open PR for the current commit and the branch it belongs to starts with `renovate/`. [_Example skipped `push` workflow run_](https://github.com/sheerlox/import-from-esm/actions/runs/6792854467)
- https://github.com/semantic-release/.github/issues/19#issuecomment-1800911730
- https://github.com/sheerlox/import-from-esm/commit/ce97a59d514f15cb65647fa5da203c2160c34617
Following the changes in #750, the `push` event on `renovate/**` branches and the `pull_request` event both trigger on Renovate PRs. [_Example PR with duplicate checks_](https://github.com/kelektiv/node-cron/pull/777)
The same mechanism is used in [`import-from-esm`](https://github.com/sheerlox/import-from-esm)'s [test workflow](https://github.com/sheerlox/import-from-esm/blob/29f …
=> ci(action): prevent duplicate checks on Renovate PRs

.github/workflows/test.yml
Due to a CI misconfiguration, Renovate was able to skip checks on PRs. This should fix the issue by skipping the `required_check` job, which gives the green light if the other jobs were skipped, for the `push` event.
=> ci: fix renovate skipping checks

.github/renovate.json
Previously Renovate would not automatically merge any package dependency version updates. This change allows Renovate to auto-merge minor and patch version updates.
This change will cut down on PR and notification noise, making maintenance easier.
=> ci: allow Renovate to auto-merge minor and patch dependency version updates

package.json
See related issue.
https://github.com/kelektiv/node-cron/issues/906
Untested, just followed the TypeScript doc: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package
=> build(typescript): add missing "types" property to package.json

.github/workflows/test.yml, .gitignore
Add support for Node v22. Keep support for v16 until we release a major version.
We want to always support at least the latest 3 LTS Node versions
Added Node v22 to the test suite
=> feat: add support for Node v22

.github/renovate.json
this should make the GitHub actions PRs a little more human readable by changing them to be pinned to semver vs. plain digests
Makes maintenance a little easier for humans
=> ci(renovate): pin GitHub action digests to semver

.vscode/launch.json, src/time.ts, tests/cron.test.ts
Removes a superfluous `+ 1` modifying the behavior unexpectedly. Using the debugger I've located the bug to this instruction, and it can easily be confirmed that this `+ 1` is the issue, since `date.month` & `this.month` are both indexed starting from `1` (and not `0`).
Not sure how long this bug has been around, but it was [already present when we aligned with the UNIX standard](https://github.com/kelektiv/node-cron/pull/667/files#diff-c14c2dca8456f15417b39cfbd9758009f8eb4f3a190a415768d6e4ae6ae9dceeL473-L477).
Fixes #919.
Fixes an infinite loop when a cron expression only resolves to inside a DST jump. See #919 for more.
Added two new test cases, and [made sure they triggered the infinite loop](https://github.com/kelektiv/node-cron/actions/runs/12539141178/attempts/1?pr=938) before …
=> fix: fix infinite loop on expressions resolving only inside a DST forward jump

.github/renovate.json
- Automerge dev dependencies & GitHub actions (except majors).
- Set dev dependencies & GitHub actions schedule: `on the 10th and 25th day of month`
- Preserve prod dependencies schedule: `at any time`
- Use `chore(action)` commit type & scope instead of `ci(action)` for GitHub actions
N/A
Too much superfluous notifications.
This is a reproduction of one of many improvements I've made to my shared configs, [see here for the full list](https://github.com/insurgent-lab/.github/commits/main/renovate?since=2024-12-25&until=2025-01-01).
N/A
=> chore(renovate): improve schedules & automerging to reduce noise

package-lock.json, package.json, src/time.ts, tests/cron.test.ts, tests/crontime.test.ts
Since v4.1.1, the timezone does not default to local system time anymore.
Fixes #971 
#971 
Added a test case with the appropriate environment variable setting.
=> fix: timezone should default to local
